services:
  repository:
    build:
      context: .
      dockerfile: Repository/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    container_name: repository
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: MyPassword123
      ACCEPT_EULA: Y
    volumes:
      - db_data:/var/opt/mssql
    container_name: mssqlserver
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 15672:15672
    container_name: rabbitmq

volumes:
  db_data:  